<?php

declare(strict_types=1);

namespace ArtisanBuild\BuiltForCloud\Testing;

use InvalidArgumentException;
use PDO;
use PDOException;
use RuntimeException;

/** A separately supplied local PostgreSQL test-administrator connection. */
final readonly class PostgresAdministrator
{
    public function __construct(
        public string $host,
        public int $port,
        public string $database,
        public string $username,
        #[\SensitiveParameter]
        public string $password,
        public string $sslMode = 'prefer',
    ) {
        if ($host === '' || $port < 1 || $port > 65535 || $database === '' || $username === '') {
            throw new InvalidArgumentException('The PostgreSQL administrator connection is invalid.');
        }

        if (! in_array($sslMode, ['disable', 'allow', 'prefer', 'require', 'verify-ca', 'verify-full'], true)) {
            throw new InvalidArgumentException('The PostgreSQL administrator SSL mode is invalid.');
        }
    }

    /** Read only administrator coordinates; the target database is always generated by the lane. */
    public static function fromEnvironment(): self
    {
        $port = getenv('PGSQL_TESTING_PORT');

        return new self(
            self::requiredEnvironment('PGSQL_TESTING_HOST'),
            $port !== false && ctype_digit($port) ? (int) $port : 5432,
            self::requiredEnvironment('PGSQL_TESTING_ADMIN_DATABASE'),
            self::requiredEnvironment('PGSQL_TESTING_USERNAME'),
            self::environment('PGSQL_TESTING_PASSWORD'),
            self::environment('PGSQL_TESTING_SSLMODE', 'prefer'),
        );
    }

    public function connect(?string $database = null): PDO
    {
        try {
            return new PDO(
                sprintf(
                    'pgsql:host=%s;port=%d;dbname=%s;sslmode=%s',
                    $this->host,
                    $this->port,
                    $database ?? $this->database,
                    $this->sslMode,
                ),
                $this->username,
                $this->password,
                [
                    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                ],
            );
        } catch (PDOException $exception) {
            throw new RuntimeException('The configured PostgreSQL administrator service is unreachable.', previous: $exception);
        }
    }

    /** @return array<string, mixed> */
    public function laravelConnection(string $target, string $applicationName, int $lockTimeoutMilliseconds): array
    {
        PostgresRunIdentity::assertDatabaseName($target);

        if ($lockTimeoutMilliseconds < 1 || $lockTimeoutMilliseconds > 60_000) {
            throw new InvalidArgumentException('The PostgreSQL lock timeout is invalid.');
        }

        return [
            'driver' => 'pgsql',
            'host' => $this->host,
            'port' => (string) $this->port,
            'database' => $target,
            'username' => $this->username,
            'password' => $this->password,
            'charset' => 'utf8',
            'prefix' => '',
            'prefix_indexes' => true,
            'search_path' => 'public',
            'sslmode' => $this->sslMode,
            'application_name' => $applicationName,
            'options' => [],
        ];
    }

    private static function requiredEnvironment(string $name): string
    {
        $value = getenv($name);

        if (! is_string($value) || $value === '') {
            throw new RuntimeException("{$name} is required for the requested PostgreSQL lane.");
        }

        return $value;
    }

    private static function environment(string $name, string $default = ''): string
    {
        $value = getenv($name);

        return is_string($value) ? $value : $default;
    }
}
