<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * The instance-side, append-only APP-ACTION audit stream (Console PRD
 * D17). A NEW table beside `credential_audit_events`, which is
 * credential-work only and is deliberately not extended: the rows live
 * in each consuming app's own database, and this migration ships in the
 * package.
 *
 * NO FREE-TEXT COLUMN (D15). `action` holds the backing value of a case
 * from a compile-time enum the app declares; `action_vocabulary` holds
 * that enum's class name, so two apps' identical slugs stay
 * distinguishable; `reason` is a closed package enum. The one string
 * that is not an identifier is `on_behalf_of` — the agency a delegated
 * operator acts for, which D4 requires — and it is issuer-minted display
 * text, bounded to 120 characters and control-character-free by the
 * assertion verifier, reaching this column from a verified assertion and
 * from nowhere else. Named here rather than glossed over.
 *
 * Append-only is enforced twice: the model throws on update/delete/
 * truncate, and — where the driver permits — database triggers abort
 * UPDATE and DELETE so raw query-builder writes cannot mutate history
 * either.
 *
 * Honest limits of the database layer, the same ones the credential
 * stream's migration states: on sqlite the triggers abort ordinary
 * UPDATE/DELETE, but anyone with schema access can DROP the trigger (or
 * use `PRAGMA writable_schema`), and direct file access rewrites
 * anything; mysql and pgsql triggers are likewise droppable by a
 * privileged connection. TRUNCATE is DDL and no row trigger sees it at
 * all. That is the stated trade: a compromised instance can tamper with
 * its own history — append-only is by construction, not cryptographic.
 * Drivers this migration does not know (sqlsrv) get model-level
 * enforcement only.
 *
 * RETENTION: nothing in this package ever deletes a row here. App-action
 * events are attribution history, the same decision already taken for
 * the shadow-actor row.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('bfc_app_action_events', function (Blueprint $table): void {
            // The stable event id D17 requires, generated by the package
            // (HasUuids) on every path.
            $table->uuid('id')->primary();

            // The app's own compile-time vocabulary: the case's backing
            // value, and the enum class it came from. 64 is
            // MetadataShape::TOKEN's own bound, which the recorder
            // enforces before the insert.
            $table->string('action', 64)->index();
            $table->string('action_vocabulary', 255);

            // The closed package reason vocabulary (AppActionReason).
            $table->string('reason', 32)->index();

            // The three principals D17 names (AppActorType), and the
            // identifier of the one that acted. A delegated actor's ref
            // is the TYPE-QUALIFIED `bfc-console:{id}` form: the actor
            // table is an ordinary auto-increment in the same id space
            // `users` occupies, so a bare `7` would read as user 7.
            $table->string('actor_type', 32)->index();
            $table->string('actor_ref', 255);

            // D4's agency, on a delegated event and never on any other.
            // The verifier's own bound is 120 characters.
            $table->string('on_behalf_of', 120)->nullable();

            $table->timestamp('occurred_at')->index();
            $table->timestamp('created_at')->nullable();
        });

        match (Schema::getConnection()->getDriverName()) {
            'sqlite' => $this->guardSqlite(),
            'mysql', 'mariadb' => $this->guardMysql(),
            'pgsql' => $this->guardPgsql(),
            default => null,
        };
    }

    public function down(): void
    {
        if (Schema::getConnection()->getDriverName() === 'pgsql' && Schema::hasTable('bfc_app_action_events')) {
            DB::statement('DROP TRIGGER IF EXISTS bfc_app_action_events_append_only ON bfc_app_action_events');
            DB::statement('DROP FUNCTION IF EXISTS bfc_app_action_events_reject_mutation()');
        }

        // sqlite and mysql triggers drop with the table.
        Schema::dropIfExists('bfc_app_action_events');
    }

    private function guardSqlite(): void
    {
        DB::unprepared(<<<'SQL'
            CREATE TRIGGER bfc_app_action_events_no_update
            BEFORE UPDATE ON bfc_app_action_events
            BEGIN
                SELECT RAISE(ABORT, 'bfc_app_action_events is append-only');
            END
            SQL);

        DB::unprepared(<<<'SQL'
            CREATE TRIGGER bfc_app_action_events_no_delete
            BEFORE DELETE ON bfc_app_action_events
            BEGIN
                SELECT RAISE(ABORT, 'bfc_app_action_events is append-only');
            END
            SQL);
    }

    private function guardMysql(): void
    {
        DB::unprepared(<<<'SQL'
            CREATE TRIGGER bfc_app_action_events_no_update
            BEFORE UPDATE ON bfc_app_action_events
            FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'bfc_app_action_events is append-only'
            SQL);

        DB::unprepared(<<<'SQL'
            CREATE TRIGGER bfc_app_action_events_no_delete
            BEFORE DELETE ON bfc_app_action_events
            FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'bfc_app_action_events is append-only'
            SQL);
    }

    private function guardPgsql(): void
    {
        DB::unprepared(<<<'SQL'
            CREATE FUNCTION bfc_app_action_events_reject_mutation() RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'bfc_app_action_events is append-only';
            END;
            $$ LANGUAGE plpgsql
            SQL);

        DB::unprepared(<<<'SQL'
            CREATE TRIGGER bfc_app_action_events_append_only
            BEFORE UPDATE OR DELETE ON bfc_app_action_events
            FOR EACH ROW EXECUTE FUNCTION bfc_app_action_events_reject_mutation()
            SQL);
    }
};
